### ISSUE TITLE
panic in status view when trying to view the diff

### ISSUE THREAD

**Issue by rupor-github** [rgburke/grv#29]
Status View, empty "Diff for unstaged files" pane, pressing "tab".

```
panic: runtime error: index out of range

goroutine 37 [running]:

main.(*DiffView).RenderHelpBar(0xc4200e6230, 0xc4205c8d80, 0x0, 0x0)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/diff_view.go:275 +0x188
main.(*ContainerView).RenderHelpBar(0xc4200d4b40, 0xc4205c8d80, 0xc4200d4b40, 0x3)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/container_view.go:241 +0xb0
main.(*View).RenderHelpBar(0xc4200d4c60, 0xc4205c8d80, 0x1, 0x0)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/view.go:289 +0xa7
main.(*HelpBarView).Render(0xc420087ba0, 0xdd3fc0, 0xc4200e63f0, 0x0, 0x0)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/help_bar_view.go:61 +0x14b
main.(*GRVStatusView).Render(0xc4200ec5c0, 0x1, 0xff, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/grv_status_view.go:90 +0x1a8
main.(*View).Render(0xc4200d4c60, 0x3d, 0xff, 0xc420b91e30, 0x0, 0x0, 0x0, 0x0)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/view.go:182 +0x47b
main.(*GRV).runDisplayLoop(0xc42009e500, 0xc4200f8d00, 0xc420084840, 0xc4200bc8c0, 0xc4200849c0)
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/grv.go:340 +0x579

created by main.(*GRV).Run
	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/grv.go:261 +0x147
```

**Comment by rgburke** [comment]
Thanks for reporting this issue. Proper index checking has been added to this function in the diff view.
