### ISSUE TITLE
Crashes when resizing the terminal

### ISSUE THREAD

**Issue by Carpetsmoker** [rgburke/grv#3]
Seems fairly consistent both when making the terminal window larger and smaller.

I'm using xterm 330 on Arch Linux.

The stack is somewhat mangled due to the ncurses stuff. I'm going to be super-lazy here and just paste it as-is without fixing the formatting it; it's still fairly readable...

```
signal SIGSEGV: segmentation violation code=0x1 addr=0x24c pc=0x7fb1e6e70277]

                                                                            runtime stack:
                                                                                          runtime.throw(0x6ed037, 0x2a)
                                                                                                                        /usr/lib/go/src/runtime/panic.go:605 +0x95
                                                                                                                                                                  runtime.sigpanc()
        /usr/lib/go/src/runtime/signal_unix.go:351 +0x2b8

                                                         goroutine 15 [syscall, locked to thread]:
                                                                                                  runtime.cgocall(0x5bb140, 0xc42003cda0, 0x300000002)
                                                                                                                                                        /usr/lib/go/src/runtime/gocall.go:132 +0xe4 fp=0xc42003cd60 sp=0xc42003cd20 pc=0x428eb4
                                                               github.com/rthornton128/goncurses._Cfunc_resizeterm(0xb10000002b, 0xc400000000)
                                                                                                                                                github.com/rthornton128/goncurse/_obj/_cgo_gotypes.go:2613 +0x4d fp=0xc42003cda0 sp=0xc42003cd60 pc=0x50f71d
                                                                            github.com/rthornton128/goncurses.ResizeTerm(0x2b, 0xb1, 0x5413, 0xc42003ce00)
                                                                                                                                                                /home/martin/go/rc/github.com/rthornton128/goncurses/ncurses.go:240 +0x37 fp=0xc42003cdc8 sp=0xc42003cda0 pc=0x510487
                                                                                                     main.(*NCursesUI).Resize(0xc4200c29b0, 0x0, 0x0)
                                                                                                                                                        /home/martin/go/src/githb.com/rgburke/grv/cmd/grv/ui.go:221 +0x143 fp=0xc42003ce40 sp=0xc42003cdc8 pc=0x5aa673
                                                                                      main.(*GRV).runSignalHandlerLoop(0xc420060420, 0xc420015160, 0xc4200164e0)
                                                                                                                                                                        /home/matin/go/src/github.com/rgburke/grv/cmd/grv/grv.go:402 +0x474 fp=0xc42003cfc8 sp=0xc42003ce40 pc=0x589114
                                                                                                       runtime.goexit()
                                                                                                                        /usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc4200cfd0 sp=0xc42003cfc8 pc=0x47db51
                                created by main.(*GRV).Run
                                                                /home/martin/go/src/github.com/rgburke/grv/cmd/grv/grv.go:230 +0x203

                                                                                                                                    goroutine 1 [semacquire]:
                                                                                                                                                             sync.runtime_Semacqire(0xc42001516c)
                        /usr/lib/go/src/runtime/sema.go:56 +0x39
                                                                sync.(*WaitGroup).Wait(0xc420015160)
                                                                                                        /usr/lib/go/src/sync/waitgroup.go:131 +0x72
                                                                                                                                                   main.(*GRV).Run(0xc420060420)
home/martin/go/src/github.com/rgburke/grv/cmd/grv/grv.go:235 +0x278
                                                                   main.main()
                                                                                /home/martin/go/src/github.com/rgburke/grv/cmd/grv/main.go:36 +0x1a7

                                                                                                                                                    goroutine 5 [syscall]:
                                                                                                                                                                          os/sigl.signal_recv(0xa12800)
                        /usr/lib/go/src/runtime/sigqueue.go:131 +0xa6
                                                                     os/signal.loop()
                                                                                        /usr/lib/go/src/os/signal/signal_unix.go:22 +0x22
                                                                                                                                         created by os/signal.init.0
                                                                                                                                                                        /usr/libo/src/os/signal/signal_unix.go:28 +0x41

                                       goroutine 12 [syscall]:
                                                              syscall.Syscall6(0x17, 0x4, 0xc420169580, 0x0, 0x0, 0x0, 0x0, 0x3, 0xc420169580, 0x0)
                                                                                                                                                        /usr/lib/go/src/syscall/m_linux_amd64.s:44 +0x5
                       syscall.Select(0x4, 0xc420169580, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0)
                                                                                        /usr/lib/go/src/syscall/zsyscall_linux_amd64.go:1374 +0xae
                                                                                                                                                  main.(*NCursesUI).GetInput(0xc00c29b0, 0x0, 0x1, 0xc420060298, 0x477fa0)
                                                /home/martin/go/src/github.com/rgburke/grv/cmd/grv/ui.go:393 +0x2c5
                                                                                                                   main.(*InputKeyMapper).GetKeyInput(0xc4200ba200, 0xc420137f170xc4200164e0, 0x0, 0x1)
                        /home/martin/go/src/github.com/rgburke/grv/cmd/grv/input_key_mapper.go:140 +0x3c
                                                                                                        main.(*GRV).runInputLoop(0xc420060420, 0xc420015160, 0xc4200164e0, 0xc4260240, 0xc420060300)
                        /home/martin/go/src/github.com/rgburke/grv/cmd/grv/grv.go:245 +0x121
                                                                                            created by main.(*GRV).Run
                                                                                                                        /home/martin/go/src/github.com/rgburke/grv/cmd/grv/grv.g224 +0xd8

         goroutine 13 [select]:
                               main.(*GRV).runDisplayLoop(0xc420060420, 0xc420015160, 0xc4200164e0, 0xc4200c0000, 0xc420060300)
                                                                                                                                /home/martin/go/src/github.com/rgburke/grv/cmd/g/grv.go:282 +0x351
                  created by main.(*GRV).Run
                                                /home/martin/go/src/github.com/rgburke/grv/cmd/grv/grv.go:226 +0x142

                                                                                                                    goroutine 14 [select]:
                                                                                                                                          main.(*GRV).runHandlerLoop(0xc42006042 0xc420015160, 0xc4200164e0, 0xc420060240, 0xc4200602a0, 0xc420060300)
                                                                        /home/martin/go/src/github.com/rgburke/grv/cmd/grv/grv.go:344 +0x260
                                                                                                                                            created by main.(*GRV).Run
                                                                                                                                                                        /home/main/go/src/github.com/rgburke/grv/cmd/grv/grv.go:228 +0x1b3

                                                          goroutine 16 [select, locked to thread]:
                                                                                                  runtime.gopark(0x6f06c8, 0x0, 0x6e35e4, 0x6, 0x18, 0x1)
                                                                                                                                                                /usr/lib/go/src/ntime/proc.go:277 +0x12c
                        runtime.selectgo(0xc420041f50, 0xc420016600)
                                                                        /usr/lib/go/src/runtime/select.go:395 +0x1138
                                                                                                                     runtime.ensureSigM.func1()
                                                                                                                                                /usr/lib/go/src/runtime/signal_ux.go:511 +0x220
               runtime.goexit()
                                /usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1
```

**Comment by rgburke** [comment]
Thanks for the bug report. I was able to reproduce this by rapidly changing the size of the terminal window in which GRV ran. The latest changes on master resolve this on my system. Could you confirm if this bug is now fixed for you?

**Comment by Carpetsmoker** [comment]
:+1: Seems to work well in a quick test.
