### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Lerentis** [rgburke/grv#48]
Hey there,

thanks for this awsome git client. have been looking for something like this for a long time now (: 
sadly i get a runtime error in one repository i have on my system.

steps to reproduce:
```
git clone https://github.com/irungentoo/toxcore.git
cd toxcore
TERM=xterm grv
```

Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x5cb045]

 goroutine 28 [running]:
main.DetermineRenderedCodePoint(0x9, 0x37, 0x0, 0x0, 0xc420185a00, 0x1, 0x1)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/window.go:533 +0x215
main.(*TableFormatter).textWidth(0xc4201a00c0, 0x23, 0x3, 0x37, 0x1e)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/table_formatter.go:235 +0xf5
main.(*TableFormatter).determineMaxColWidths(0xc4201a00c0, 0x1)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/table_formatter.go:220 +0xb0
main.(*TableFormatter).PadCells(0xc4201a00c0, 0x1, 0xc420259717, 0x3)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/table_formatter.go:180 +0x4c
main.(*TableFormatter).Render(0xc4201a00c0, 0xde3fc0, 0xc42011a150, 0x1, 0x1, 0x0, 0x0)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/table_formatter.go:144 +0x5f
main.(*CommitView).Render(0xc420092400, 0xde3fc0, 0xc42011a150, 0x0, 0x0)                                                                                                                                  	/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/commit_view.go:136 +0x47e
main.(*ContainerView).renderWindowView(0xc420108870, 0xde3020, 0xc420092400, 0xc420134ae0, 0xc420092400, 0x1, 0x8)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/container_view.go:386 +0xd6
 main.(*ContainerView).Render(0xc420108870, 0x40, 0xef, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/container_view.go:280 +0x374
main.(*ContainerView).Render(0xc420108990, 0x40, 0x112, 0xc420174028, 0x1, 0x1, 0x0, 0x0)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/container_view.go:289 +0x51d
main.(*View).Render(0xc420108c60, 0x43, 0x112, 0xc42012c170, 0x0, 0x0, 0x0, 0x0)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/view.go:161 +0x27d
main.(*GRV).runDisplayLoop(0xc420092500, 0xc420142350, 0xc420078960, 0xc4200f08c0, 0xc420078ae0)
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/grv.go:340 +0x579
created by main.(*GRV).Run
/home/richard/code/goworkspace/src/github.com/rgburke/grv/cmd/grv/grv.go:261 +0x147
```

I am using the install methode as mentioned in the README
```
wget -O grv https://github.com/rgburke/grv/releases/download/v0.1.2/grv_v0.1.2_linux64
chmod +x ./grv
sudo mv grv /usr/bin/
```

**Comment by rgburke** [comment]
Thanks for reporting this bug! It caused GRV to crash whenever a commit summary contained a tab character. I'm surprised no one has encountered this before.

This is now fixed on master, I've tested it using the `github.com/irungentoo/toxcore` repository.

**Comment by Lerentis** [comment]
Thank you for the fast fix :smiley_cat:
